import './globals.css';
import { Roboto } from 'next/font/google'
import Nav from './auth/Nav';

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`mx-4 md:mx-48 xl:mx-96 ${roboto.className}`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
